# DEVELOPMENT

services:
  app:
    build:
      target: dev-stage

    develop:
      watch:
        - action: rebuild
          path: .env

        - action: sync
          path: ./api/src
          target: /gatherzap/api/src

        - action: sync
          path: ./app/web/src
          target: /gatherzap/app/web/src

        - action: sync
          path: ./app/web/public
          target: /gatherzap/app/web/public

        - action: rebuild
          path: ./app/web/package.json
          target: /gatherzap/app

        - action: rebuild
          path: ./app/web/eslint.config.mjs
          target: /gatherzap/app

        - action: rebuild
          path: ./app/web/tsconfig.json
          target: /gatherzap/app

        - action: rebuild
          path: ./app/web/next.config.ts
          target: /gatherzap/app

        - action: rebuild
          path: ./app/web/postcss.config.mjs
          target: /gatherzap/app

        - action: rebuild
          path: ./app/web/tailwind.config.ts
          target: /gatherzap/app

  api:
    build:
      target: dev-stage

    develop:
      watch:
        - action: rebuild
          path: .env

        - action: sync
          path: ./api/src
          target: /gatherzap/api/src

        - action: rebuild
          path: ./api/package.json
          target: /gatherzap/api

        - action: rebuild
          path: ./api/tsconfig.json
          target: /gatherzap/api
