# DEVELOPMENT

services:
  api:
    build:
      target: dev-stage

    develop:
      watch:
        - action: sync
          path: ./api/src
          target: /app/src

        - action: rebuild
          path: ./api/package.json
          target: /app

        - action: rebuild
          path: ./api/tsconfig.json
          target: /app
