services:
  app:
    container_name: app

    profiles:
      - production
      - development

    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./app
      args:
        PORT: ${APP_PORT}

    ports:
      - ${APP_PORT}:${APP_PORT}

  api:
    container_name: api

    profiles:
      - production
      - development

    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./api
      args:
        ENVIRONMENT: ${ENVIRONMENT}
        PORT: ${API_PORT}

    ports:
      - "${API_PORT}:${API_PORT}"

    volumes:
      - ./api/prisma:/app/prisma

  db:
    container_name: db

    profiles:
      - production
      - development

    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./db
      args:
        PORT: 5432
        PASSWORD: ${DATABASE_PASSWORD}
        DATABASE_NAME: ${DATABASE_NAME}

    volumes:
      - ./db/volumes/data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin

    profiles:
      - production
      - development

    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./pgadmin
      args:
        PORT: 8080
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}

    ports:
      - 8080:8080
    volumes:
      - ./pgadmin/volumes/data:/var/lib/pgadmin
