services:
  app:
    container_name: app

    profiles:
      - production
      - development

    restart: always
    build:
      dockerfile: ./app/Dockerfile
      # NOTE: Give access to other service folders
      context: ./
      args:
        ENVIRONMENT: ${ENVIRONMENT}
        PORT: ${APP_PORT}
        CLERK_PUBLISHABLE_KEY: ${CLERK_PUBLISHABLE_KEY}
        GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
        COMING_SOON_MODE: ${COMING_SOON_MODE}
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        SOCIAL_LINK: ${SOCIAL_LINK}

    ports:
      - ${APP_PORT}:${APP_PORT}

    volumes:
      - ./app/volumes/root/.cache:/root/.cache

  api:
    container_name: api

    profiles:
      - production
      - development

    restart: always
    build:
      dockerfile: ./api/Dockerfile
      # NOTE: Give access to other service folders
      context: ./
      args:
        ENVIRONMENT: ${ENVIRONMENT}
        PORT: ${API_PORT}
        DATABASE_URL: ${DATABASE_URL}
        CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
        CLERK_PUBLISHABLE_KEY: ${CLERK_PUBLISHABLE_KEY}
        COMING_SOON_MODE: ${COMING_SOON_MODE}

    ports:
      - "${API_PORT}:${API_PORT}"

    volumes:
      - ./api/prisma:/gatherzap/api/prisma

  db:
    container_name: db

    profiles:
      - production
      - development

    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./db
      args:
        PORT: 5432
        PASSWORD: ${DATABASE_PASSWORD}
        DATABASE_NAME: ${DATABASE_NAME}

    volumes:
      - ./db/volumes/data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin

    profiles:
      - production
      - development

    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./pgadmin
      args:
        PORT: ${PGADMIN_PORT}
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}

    ports:
      - ${PGADMIN_PORT}:${PGADMIN_PORT}
    volumes:
      - ./pgadmin/volumes/data:/var/lib/pgadmin
